Fix NLU re-exporting symbols issues
snipsco/hermes-protocol pull request #127
Opened 2019-06-17 11:44 UTC by Deluvi

As of right now, it is mandatory to add as a dependency the `snips-nlu-ontology` crate to use some of the NLU ontology contained in the `NluIntentMessage` for example.

With this addition, the `hermes` crate is now exporting the ontology used by the structures exported by Hermes.

2019-07-05 11:54 UTC, adrienball commented
IMO, it would be better to export everything through `pub use snips_nlu_ontology::*;`
Currently, you have only exported top level objects, but underlying objects are not exposed (for instance the `Precision` attribute of `AmountOfMoneyValue`).
There are quite many so listing them exhaustively is tedious, plus it will need to be maintained.

WDYT @fredszaq ?

2019-07-11 09:18 UTC, fredszaq commented
seems like a good idea to use a `::*` to facilitate maintenance indeed. However I would mode the pub use inside a public `nlu_ontology` module, that way we don't pollute the hermes namespace with the nlu ontology structs and we prevent ourselves from problems if we end up having the same struct name in the nlu ontology and hermes at some time (which should not happen be we never know)

2019-07-11 09:19 UTC, fredszaq requested changes
see comment

2019-07-11 11:36 UTC, fredszaq approved these changes

2019-07-11 11:36 UTC, merged